table_name: projects
table_comment: 'Contains project table'
fields:
  title:
    type: short_text
    column_name: title
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Project title'
    length: '255'
  description:
    type: long_text
    column_name: description
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
